# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-3d2268fe-5c8f-42d8-a02d-d500f2df7319";
      fsType = "xfs";
    };

  boot.initrd.luks.devices."luks-3d2268fe-5c8f-42d8-a02d-d500f2df7319".device = "/dev/disk/by-uuid/3d2268fe-5c8f-42d8-a02d-d500f2df7319";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/39E8-8394";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-65f6a6d1-31e0-4bf5-bf13-cbc7705a1163"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  
}
