{
  imports = [
    ./base.nix
    ./users.nix
    ./locale.nix
    ./networking.nix
    ./tailscale.nix
    ./audio.nix
    ./ssh.nix
    ./laptop-input.nix
    ./keyboard.nix
    ./virtualisation.nix
    ./cross-compile.nix
    ./boot
    ./desktop
    ./hardware
    ./programs
  ];
}
